name: Production deployment from master

on: 
  push:
    branches:
      - master

env:
  DBT_PROFILE_TARGET:            prod
  DBT_PROFILE_SNOWFLAKE_ACCOUNT: hg27825.ap-south-1.aws
  DBT_PROFILE_USER:              aschouhan8@gmail.com 
  DBT_PROFILE_PASSWORD:          Sanvi@2912
  DBT_PROFILE_ROLE:              sysadmin
  DBT_PROFILE_DB:                demo_db
  DBT_PROFILE_SCHEMA:            jaffle_shop
  DBT_PROFILE_WH:                compute_wh

jobs:
  prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Install Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install DBT
      run: |
        python -m pip install --upgrade pip
        pip install dbt
    - name: Deploy
      run: |
        dbt test  
